#!/bin/bash
if ! websmc_payara_deploy; then
  #curl -s -X POST https://api.telegram.org/botTOKEN/sendMessage -d chat_id=CHATID -d text="PROJ VERSION Payara deploy failed!" &> /dev/null
  echo "Payara deploy failed!"
fi