#!/bin/bash
# Post install
export pinst="no match"
export enough="f"
export pcount=1
until [ "$enough" == "t" ]
do
 echo "Running post_install $pcount"
 let pcount++
 post_install_sql &> ~/post_install_sql.log
 grep -5 ORA ~/post_install_sql.log > post_install_sql.err.log
 sed -i /^Elapsed/d post_install_sql.err.log
 if [ "$pinst" == "$(md5sum post_install_sql.err.log)" ] ; then
 export enough="t"
 fi
 export pinst="$(md5sum post_install_sql.err.log)"
done
#tgmesg "Please review post_install error log."
#tgfile post_install_sql.err.log
